print("Hello, World!")
print("Blah blah blah")
print("Goodbye, world")
print("Hello, World!")
print("Blah blah blah")
print("Goodbye, world")
print("Hello, World!")
print("Blah blah blah")
print("Goodbye, world")
print("Hello, World!")
print("Blah blah blah")
print("Goodbye, world")
print("Hello, World!")
print("Blah blah blah")
print("Goodbye, world")
